# Generated by Django 3.2 on 2021-04-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='Employer_job',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name=''),
        ),
        migrations.AddField(
            model_name='employer',
            name='fullname',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='employer',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
