# Generated by Django 3.1.5 on 2021-01-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('upload_Image', models.ImageField(default='True', upload_to='uploads/')),
                ('description', models.TextField(max_length=250)),
                ('product_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('manufacturer', models.CharField(blank=True, max_length=300)),
                ('price_in_rupees', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
