# Generated by Django 3.1.5 on 2021-01-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_auto_20210121_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
