# Generated by Django 3.1.5 on 2021-01-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_auto_20210121_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
