# Generated by Django 3.1.5 on 2021-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_remove_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('T', 'T-shirt'), ('S', 'Shirt'), ('W', 'Watch')], max_length=5, null=True),
        ),
    ]
