# Generated by Django 3.1.5 on 2021-03-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
