# Generated by Django 3.2 on 2021-04-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210421_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Dispatch', 'Dispatch'), ('Cancelled', 'Cancelled')], max_length=100, null=True),
        ),
    ]
