# Generated by Django 3.2 on 2021-06-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_ref',
            field=models.CharField(default='1BE6262B7870', editable=False, max_length=12),
        ),
    ]
